### ISSUE TITLE
Can you help fix my corrupt exe.xml file?

### ISSUE THREAD

**Issue by DH174** [RoystonS/BetterBravoLights#11]
**Software version**
0.4.0

**Problem**
BetterBravoLights refused to install because my `exe.xml` file is corrupt.

My `exe.xml` file is located at
`C:\Users\User\AppData\Roaming\Microsoft Flight Simulator\exe.xml`

The error reported was
```
Unexpected end tag. Line 7, position 3.
```

The contents of the `exe.xml` file are as follows:

```xml
<?xml version="1.0" encoding="Windows-1252"?>
  <Launch.Addon>
    <Name>AFCBridge</Name>
    <Disabled>False</Disabled>
    <Path>C:\Users\User\AppData\Roaming\Microsoft Flight Simulator\Packages\community\AFC_Bridge\bin\AFC_Bridge.exe</Path>
   </Launch.Addon>
</SimBase.Document>



```

I understand that BetterBravoLights didn't corrupt the file and that it's simply warning
about the corrupted file. But could you help me fix it?

**Comment by RoystonS** [comment]
Ah, excellent. Yep, looks like there's a missing leading `<SimBase.Document>`.

Interesting.  Looks like the only other software you have is the Honeycomb AFC Bridge. Ever tried to install any other similar software?

**Comment by DH174** [comment]
Nope only AFC Bridge.
