### ISSUE TITLE
Low HYD Pressure

### ISSUE THREAD

**Issue by JimHerrod** [RoystonS/BetterBravoLights#15]
You're doing an excellent job on the A32NX config and I like the way the APU and ANTI ICE lights now behave. One item that may need to be revisited is the Low HYD pressure light. It remains always on and according to the expression, it should only be lit if the blue, green or yellow pressures are below 2000 psi. As shown below, my pressures are at a constant 3000 psi in the aircraft, but the light remains illuminated. Also, if I'm understanding the debugger correctly, it looks like the software is seeing values of 0 on all 3 hyd systems

![Capture2](https://user-images.githubusercontent.com/20194323/137784523-b6af6148-a909-40e6-8c38-68f17ace5d9f.PNG)
![Capture3](https://user-images.githubusercontent.com/20194323/137784539-fa05cb48-798c-4881-ae98-f059108c15d3.PNG)

**Comment by JimHerrod** [comment]
That may be my issue. I don’t think I have the WASM module enabled in FSUIPC7. I will reinstall it and enable WASM, then update you on the results

**Comment by JimHerrod** [comment]
I enabled WASM and BBL is still pulling in values of zero, unfortunately. I believe I have other lvars working through Lorby Axis and Ohs, which I'm using for the AP switches and dials on the Bravo.

Let me know if you need any additional details.

**Comment by RoystonS** [comment]
Ok, so let's check to see if FSUIPC7 is exposing the lvars correctly first.

If you open up the FSUIPC7 window and click `Add-ons->WASM->List lvars`, does it show the lvars in the FSUIPC7 window?

Here's how it looks for me:

**Comment by JimHerrod** [comment]
I confirmed the lvars are populated in FSUIPC7. I pasted the ones that reference hyd functionalitity below, in case you wanted to take a look.

A32NX_HYD_ELECPUMPLOCK_TOGGLE = 0.000000
A32NX_HYD_ELECPUMPY_FAULT = 0.000000
A32NX_HYD_ELECPUMPY_TOGGLE = 0.000000
A32NX_HYD_ELECPUMP_FAULT = 0.000000
A32NX_HYD_ELECPUMP_TOGGLE = 0.000000
A32NX_HYD_ENG1PUMP_FAULT = 0.000000
A32NX_HYD_ENG1PUMP_TOGGLE = 0.000000
A32NX_HYD_ENG2PUMP_FAULT = 0.000000
A32NX_HYD_ENG2PUMP_TOGGLE = 0.000000
A32NX_HYD_GREEN_EDPUMP_ACTIVE = 1.000000
A32NX_HYD_GREEN_EDPUMP_LOW_PRESS = 1.000000
A32NX_HYD_GREEN_FIRE_VALVE_OPENED = 1.000000
A32NX_HYD_GREEN_PRESSURE = 14.700000
A32NX_HYD_GREEN_RESERVOIR = 3.600000
A32NX_HYD_PTU_ACTIVE_L2R = 0.000000
A32NX_HYD_PTU_ACTIVE_R2L = 0.000000
A32NX_HYD_PTU_FAULT = 0.000000
A32NX_HYD_PTU_HIGH_PITCH_SOUND = 0.000000
A32NX_HYD_PTU_MOTOR_FLOW = 0.000000
A32NX_HYD_PTU_TOGGLE = 0.000000
A32NX_HYD_PTU_VALVE_OPENED = 1.000000
A32NX_HYD_RAT_RPM = 0.000000
A32NX_HYD_RAT_STOW_POSITION = 0.000000
A32NX_HYD_YELLOW_EDPUMP_ACTIVE = 1.000000
A32NX_HYD_YELLOW_EDPUMP_LOW_PRESS = 1.000000
A32NX_HYD_YELLOW_EPUMP_ACTIVE = 0.000000
A32NX_HYD_YELLOW_EPUMP_FLOW = 0.000000
A32NX_HYD_YELLOW_EPUMP_LOW_PRESS = 0.000000
A32NX_HYD_YELLOW_FIRE_VALVE_OPENED = 1.000000
A32NX_HYD_YELLOW_PRESSURE = 14.700000
A32NX_HYD_YELLOW_RESERVOIR = 3.600000

**Comment by JimHerrod** [comment]
Update...I just noticed that the light was turned off a few minutes into my flight. May have needed a sim restart for the WASM module to link up. I will keep an eye on it and see exactly at what conditions caused it to turn off, and give you another update. Thanks.

**Comment by jcabanascachi** [comment]
That happens to me sometimes, I have to go to FSUIPC7 console, then Add-ons, WASM and reload, after that, Better Bravo Lights starts to work ok again and reads correctly the LVARs

**Comment by JimHerrod** [comment]
I can confirm the issue with the HYD pressure light is resolved. Just needed a sim and/or FSUIPC7 restart. Keep up the great work!

**Comment by RoystonS** [comment]
Excellent. I'll close this issue and keep working on the improvements to lvar reading and (as importantly) lvar error reporting. Specifically, I want to be able to report if lvars aren't working. With the API I'm using right now I can't do that: they just read 0 if there are any problems at all.
