### ISSUE TITLE
Can you help fix my corrupt exe.xml file?

### ISSUE THREAD

**Issue by jstorey20** [RoystonS/BetterBravoLights#18]
**Software version**
0.6.0

**Problem**
BetterBravoLights refused to install because my `exe.xml` file is corrupt.

My `exe.xml` file is located at
`C:\Users\jstor\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\exe.xml`

The error reported was
```
Unexpected end tag. Line 7, position 3.
```

The contents of the `exe.xml` file are as follows:

```xml
<?xml version="1.0" encoding="Windows-1252"?>
  <Launch.Addon>
    <Name>AFCBridge</Name>
    <Disabled>False</Disabled>
    <Path>G:\Base Sim\community\AFC_Bridge\bin\AFC_Bridge.exe</Path>
   </Launch.Addon>
</SimBase.Document>



```

I understand that BetterBravoLights didn't corrupt the file and that it's simply warning
about the corrupted file. But could you help me fix it?

**Comment by RoystonS** [comment]
Hi @jstorey20

Your `exe.xml` file is missing the initial `<SimBase.Document>` open tag.
So the file _should_ be:

```
<?xml version="1.0" encoding="Windows-1252"?>
<SimBase.Document>
  <Launch.Addon>
    <Name>AFCBridge</Name>
    <Disabled>False</Disabled>
    <Path>G:\Base Sim\community\AFC_Bridge\bin\AFC_Bridge.exe</Path>
  </Launch.Addon>
</SimBase.Document>
```

**Comment by RoystonS** [comment]
No problem. Did it fix it okay?

**Comment by jstorey20** [comment]
Sorry this a bit late but yes working ok now thanks again

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by RoystonS** [comment]
Great stuff!
