### ISSUE TITLE
Didn't "install" and didn't work

### ISSUE THREAD

**Issue by vgbaron** [RoystonS/BetterBravoLights#19]
**Software version** 0.60

**Describe the bug**

Had installed AFC Bridge and the folder was present in my Community folder. Downloaded Bravo from flightsim.to and extracted contents to dedicated folder on my E drive. Run install.bat as admin. No change from Bridge results. Look in Community folder and bridge folder is still present and working. Ran uninstall.bat. Manually removed bridge folder. Run install.bat . Noticed no change in community folder. Took flight , no lights working at all. Restore bridge folder - lights working

**To reproduce**
tried same steps three times wirth same results - evidently Bravo is not installing.

**Expected behavior**

Um, I expected the lights to work - they did not.

**Screenshots**

**Other software**

- MSFS: Windows Store edition or Steam? Store
- FSUIPC: Do you use FSUIPC?
 Yes
**Additional context**

Otyer than not working there was no damage or problem caused by Bravo - just didn't work.

FWIW, my MSFS install is on my F: drive.

**Comment by RoystonS** [comment]
When you run `install.bat` what actually happens? I'd expect to see something like this:
![image](https://user-images.githubusercontent.com/19773/140916019-9be50ae9-760a-40e0-9df6-a7d2e94f6380.png)

Btw, you don't need to run as admin unless your normal user doesn't have write access to your Flight Simulator folder or Community folder.

(I've never tried running it as admin.)

**Comment by vgbaron** [comment]
I get a quick cmd box flash and that’s it

**Comment by vgbaron** [comment]
I’ll give it a shot when I get home.

Thanx!

**Comment by vgbaron** [comment]
ok, got the proper dialog etc NOT running as admin. I see the BBL splash screen when MSFS loads. I also see that the AFC Bridge folder is still in community. Should that still remain there?

However, so far all seems to work.

Thanx for your help,

Vic
________________________________

**Comment by RoystonS** [comment]
Yep, BBL doesn't remove the AFC Bridge folder. (Which doesn't actually need to be in the Community folder at all, as it turns out. Not really sure why they put it there.)  BBL simply modifies the file that controls what runs when the simulator starts, and arranges for BBL to run instead of AFC.  If you uninstall BBL, it'll modify that file back again to restore AFC.

I'll modify the installation instructions to tell people they _don't_ need to run as administrator.
