### ISSUE TITLE
Change LVARs for FBW A32NX LOW HYD PRESSURE light

### ISSUE THREAD

**Issue by jcabanascachi** [RoystonS/BetterBravoLights#21]
**Software version**
0.6.0

**Is your feature request related to a problem? Please describe.**

Hi @RoystonS  It is me again, I was flying today and I realised that FBW team changed some LVars again, I am talking about pressure LVars, the ones you have by default config (L:A32NX_HYD_BLUE_PRESSURE < 2000 OR L:A32NX_HYD_GREEN_PRESSURE < 2000 OR L:A32NX_HYD_YELLOW_PRESSURE < 2000) do not longer exist.

**Describe the solution you'd like**

The new LVars are: 

LowHydPressure = L:A32NX_HYD_BLUE_SYSTEM_1_SECTION_PRESSURE < 2000 OR L:A32NX_HYD_GREEN_SYSTEM_1_SECTION_PRESSURE < 2000 OR L:A32NX_HYD_YELLOW_SYSTEM_1_SECTION_PRESSURE < 2000

**Describe alternatives you've considered**

There are also this variables: 

L:A32NX_HYD_BLUE_PUMP_1_SECTION_PRESSURE and same for green and yellow systems, but I am not sure yet wich ones are correct. I have already changed them in my config file (the ones in "describe the solution you would like" section) and it seems to me they are working like the previous ones.

**Additional context**

The rest of the lights seem to be working just like before.

**Comment by RoystonS** [comment]
Thank you! This will be in the updated internal config file, releasing shortly...
https://github.com/RoystonS/BetterBravoLights/commit/ea5b0329006a7360227e1caa093cc052e03b881f

**Comment by RoystonS** [comment]
I just released v0.7.0 which includes this - thank you!
