### ISSUE TITLE
Can you help fix my corrupt exe.xml file?

### ISSUE THREAD

**Issue by grandfred29** [RoystonS/BetterBravoLights#27]
**Software version**
0.6.0

**Problem**
BetterBravoLights refused to install because my `exe.xml` file is corrupt.

My `exe.xml` file is located at
`C:\Users\fred\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\exe.xml`

The error reported was
```
Unexpected end tag. Line 2, position 3.
```

The contents of the `exe.xml` file are as follows:

```xml
<?xml version="1.0" encoding="Windows-1252"?>
</SimBase.Document>


```

I understand that BetterBravoLights didn't corrupt the file and that it's simply warning
about the corrupted file. But could you help me fix it?

**Comment by grandfred29** [comment]
solved

**Comment by RoystonS** [comment]
Missing opening `<SimBase.Document>` tag. Seems to be a common problem!
