### ISSUE TITLE
Can you help fix my corrupt exe.xml file?

### ISSUE THREAD

**Issue by macinati** [RoystonS/BetterBravoLights#28]
**Software version**
0.6.0

**Problem**
BetterBravoLights refused to install because my `exe.xml` file is corrupt.

My `exe.xml` file is located at
`C:\Users\aless\AppData\Roaming\Microsoft Flight Simulator\exe.xml`

The error reported was
```
Unexpected end tag. Line 7, position 3.
```

The contents of the `exe.xml` file are as follows:

```xml
<?xml version="1.0" encoding="Windows-1252"?>
  <Launch.Addon>
    <Name>AFCBridge</Name>
    <Disabled>False</Disabled>
    <Path>E:\Steam\steamapps\common\MicrosoftFlightSimulator\community\AFC_Bridge\bin\AFC_Bridge.exe</Path>
   </Launch.Addon>
</SimBase.Document>


```

I understand that BetterBravoLights didn't corrupt the file and that it's simply warning
about the corrupted file. But could you help me fix it?

**Comment by RoystonS** [comment]
Hiya @macinati,

This seems to be a common problem - this is the second of these just today in fact!

Your `exe.xml` file is missing the opening `<SimBase.Document` line near the top.

Edit your `exe.xml` file and add in the missing second line, making your file:

```
<?xml version="1.0" encoding="Windows-1252"?>
<SimBase.Document Type="SimConnect" version="1,0">
  <Launch.Addon>
    <Name>AFCBridge</Name>
    <Disabled>False</Disabled>
    <Path>E:\Steam\steamapps\common\MicrosoftFlightSimulator\community\AFC_Bridge\bin\AFC_Bridge.exe</Path>
   </Launch.Addon>
</SimBase.Document>
```

**Comment by RoystonS** [comment]
Hi @macinati,

I'm going to assume that's fixed it and close this. I'm about to release 0.7.0 of BetterBravoLights which itself is able to auto-fix this exact common problem.
