### ISSUE TITLE
World Map Malfunction

### ISSUE THREAD

**Issue by Alex270176** [RoystonS/BetterBravoLights#34]
**Software version**

0.7.0

**Describe the bug**

I found an issue related to sim world map. If i install Better Bravo light it is not possible to insert a third point between an A -B route. In other words, i make a flight plan from an A airport to B airport and the sim shows the lines that connect the two airport. But if i want to insert a POI between the A-B route it is not possible because the voice menu ADD that appears when you click on a POI is not clickable. I hope you can understand what i am saying. Let me know otherwise. If i uninstall the Better Bravo Light the problem disappear.

**To reproduce**

1. Go to 'World Map'
2. Make a Leg from an airport to another once
3. Try to insert an intermediate POI between the A and B airport
4. You should notice that you cannot click on ADD of POI menu

- MSFS: Windows Store edition or Steam?
- Windows Store Edition

**Comment by RoystonS** [comment]
Hi @Alex270176 

I'm unable to reproduce this. I get the same behaviour (being able to click on the ADD button) whether BBL is installed or not, both for POIs and custom locations:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/19773/159751114-7c078ea2-6009-4c7e-a9f6-030bf13f19ca.png">

The only thing that BBL does is to read simulation state variables so I'm not sure how it _could_ interfere with the map.

Can you reinstall BBL and try again?

**Comment by RoystonS** [comment]
Other users are reporting this without BBL installed, and original reporter has confirmed it's not a BBL issue.
https://flightsim.to/file/21253/better-bravo-lights/266485

**Comment by Alex270176** [comment]
Ok thanks for your answer. I will try to reinstall and will let you know

Best regards
Alex

Il Mer 23 Mar 2022, 17:43 Royston Shufflebotham ***@***.***>
ha scritto:
