### ISSUE TITLE
Installer has no effect

### ISSUE THREAD

**Issue by Viking-Lead** [RoystonS/BetterBravoLights#35]
*Hi, I downloaded your tool version 0.7.0. I unzipped it and run the installer. The black window opens for a split second and closes again.
I then run MSFS, but there are no lights at all. I reboot and try again: The lights are there. Next and all later attempts: no lights at all.

I use MSFS: Windows Store edition

I tried to download and install the AFC Bridge fom Honeycomb/Aerosoft, run your uninstaller, but there are no lights either. Since they worked once, I assume that the LEDs are ok.
Any help would be appreciated.
Thanks!
Cheers
Gunter

**Comment by RoystonS** [comment]
Hi @Viking-Lead. How did you run the installer? Did you double-click on the `install.bat` file?

**Comment by Viking-Lead** [comment]
Yes, exactly! Since the black window opened shortly I assumed it did it’s trick
Cheers
Gunter 

Von meinem iPhone gesendet

**Comment by RoystonS** [comment]
You should see the black window briefly and _then_ a confirmation message like this:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/19773/162638432-070e2716-e3d7-45a1-a0b7-9fe2a0871323.png">

I take it you're not seeing that confirmation message?

**Comment by RoystonS** [comment]
If you're not seeing that confirmation message, something funny is going on, in which case, would you mind helping to gather some diagnostics?

1. Unpack the installation zip, but before you run `install.bat`, create a file named `BetterBravoLights.exe.nlog` inside the `Program` folder, containing the contents of this link: https://raw.githubusercontent.com/RoystonS/BetterBravoLights/main/BetterBravoLights.exe.nlog
1. Then run `install.bat`. Hopefully you'll see a file created named `Diagnostics.log`, next to `install.bat`. Paste the contents of that file to a comment in this issue.
Here's what I see in that file:
```
2022-04-10 21:28:58.5813 34976 DEBUG [App] Starting
2022-04-10 21:28:58.5943 34976 DEBUG [App] Arguments /install
2022-04-10 21:29:00.8479 34976 DEBUG [App] Install:Exit
```

**Comment by Viking-Lead** [comment]
Thanks, I do not see the confirmation message. I will follow your advice when I’m back from work and report back.

Von meinem iPhone gesendet

**Comment by Viking-Lead** [comment]
Thanks again, problem solved. I downloaded your tool again and run it from a folder instead from the desktop. Now everything works as designer.
Great tool!
Cheers
Gunter 

Von meinem iPhone gesendet

**Comment by RoystonS** [comment]
Interesting. I've tried installing it from a folder on the desktop, and it works fine.  I've also tried a folder with a space in the name, on the desktop. That doesn't fail either. Very odd.

I'm glad you've got it working.

But I'm curious to know why it was failing, in case somebody else has the same problem.

Would you be happy to tell me the full file path to your desktop installation folder?
e.g. mine is `C:\Users\royston\OneDrive\Desktop\BetterBravoLights WtiJo`

**Comment by Viking-Lead** [comment]
Sure, it is
C: \ Users \Gunter \Desktop \BetterBravoLights

And one more remark: After it worked once from the Own Programs Folder, it now works also from the desktop. Maybe I had a corrupt download?
Cheers
Gunter

Von meinem iPad gesendet
