### ISSUE TITLE
Add one more button for the PMDG 737-700

### ISSUE THREAD

**Issue by Flintstone2k12** [RoystonS/BetterBravoLights#46]
### Software version

0.8.1

### Problem

Light on REV button for VNav function

### Suggested solution

The 737 does not have a Backcourse, but uses this button REV to enable VNav.
Put in the PMDG 737-700 section of  the Config.Buildin.ini this extra code:

REV = L:ngx_MCP_VNav > 0

Works great for me!

**Comment by RoystonS** [comment]
Great stuff - thank you!

**Comment by RoystonS** [comment]
This just shipped in BBL 0.8.2. Thanks so much, @Flintstone2k12 !
