### ISSUE TITLE
Repair a corrupt xml.exe file

### ISSUE THREAD

**Issue by TParrine85champ** [RoystonS/BetterBravoLights#52]
### Software version

0.8.2

### What are you trying to do?

install and have the led lights operational on the Bravo throttle quadrant

### What's the problem?

honeycomb software not working and trying to install betterbravolights

### What have you tried already?

all you tube suggestions, nothing works

### Other information

I have attached my xml.exe and cant fix it or identify corruption. can you help fix it?   Thanks,  Tom
```
<?xml version="1.0" encoding="Windows-1252"?>
<SimBase.Document Type="Launch" version="1,0">
	<Descr>Launch</Descr>
	<Filename>exe.xml</Filename>
	<Disabled>False</Disabled>
	<Launch.ManualLoad>False</Launch.ManualLoad>
	<Launch.Addon>
		<Name>FenixA320</Name>
		<Disabled>False</Disabled>
		<Path>C:\Program Files\FenixSim A320\deps\FenixBootstrapper.exe</Path>
  <Launch.Addon>
    <Name>AFCBridge</Name>
    <Disabled>False</Disabled>
    <Path>C:\Users\purpl\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\community\AFC_Bridge\bin\AFC_Bridge.exe</Path>
   </Launch.Addon>
</SimBase.Document>
```

**Comment by RoystonS** [comment]
Hi @TParrine85champ.

There's a missing `</Launch.Addon>` at the end of the FenixA320 block. It amazes me how badly these tools mangle this simple XML file.

Here's a fixed version:
```
<?xml version="1.0" encoding="Windows-1252"?>
<SimBase.Document Type="Launch" version="1,0">
	<Descr>Launch</Descr>
	<Filename>exe.xml</Filename>
	<Disabled>False</Disabled>
	<Launch.ManualLoad>False</Launch.ManualLoad>
	<Launch.Addon>
		<Name>FenixA320</Name>
		<Disabled>False</Disabled>
		<Path>C:\Program Files\FenixSim A320\deps\FenixBootstrapper.exe</Path>
	</Launch.Addon>
  <Launch.Addon>
    <Name>AFCBridge</Name>
    <Disabled>False</Disabled>
    <Path>C:\Users\purpl\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\community\AFC_Bridge\bin\AFC_Bridge.exe</Path>
   </Launch.Addon>
</SimBase.Document>
```

**Comment by RoystonS** [comment]
Out of interest, did you install the Honeycomb drivers before the A320 addon or afterwards?  (I'm interested to know which one broke the file.)

**Comment by RoystonS** [comment]
This is now the second broken `exe.xml` file I've seen, with the Fenix A320 in it and exactly the same problem.
See also #53
