### ISSUE TITLE
Can you help fix my corrupt exe.xml file?

### ISSUE THREAD

**Issue by cigayi** [RoystonS/BetterBravoLights#53]
### Software version

0.8.2

### Location of my exe.xml file

C:\Users\cigay\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\exe.xml

### Contents of my exe.xml file

```xml
<?xml version="1.0" encoding="Windows-1252"?>
<SimBase.Document Type="Launch" version="1,0">
	<Descr>Launch</Descr>
	<Filename>exe.xml</Filename>
	<Disabled>False</Disabled>
	<Launch.ManualLoad>False</Launch.ManualLoad>
	<Launch.Addon>
		<Name>FenixA320</Name>
		<Disabled>False</Disabled>
		<Path>C:\Program Files\FenixSim A320\deps\FenixBootstrapper.exe</Path>
</SimBase.Document>
```

### The installation error

```text
The 'Launch.Addon' start tag on line 7 position 3 does not match the end tag of 'SimBase.Document'. Line 11, position 3.
```

**Comment by RoystonS** [comment]
Hi @cigayi

Your `exe.xml` file is missing a close `</Launch.Addon>` line just before the end. Here's what you need:

```
<?xml version="1.0" encoding="Windows-1252"?>
<SimBase.Document Type="Launch" version="1,0">
	<Descr>Launch</Descr>
	<Filename>exe.xml</Filename>
	<Disabled>False</Disabled>
	<Launch.ManualLoad>False</Launch.ManualLoad>
	<Launch.Addon>
		<Name>FenixA320</Name>
		<Disabled>False</Disabled>
		<Path>C:\Program Files\FenixSim A320\deps\FenixBootstrapper.exe</Path>
	</Launch.Addon>
</SimBase.Document>
```

Out of interest, could I ask what addons you've installed and uninstalled in the past? Your `exe.xml` file only seems to have one thing in it, and that's broken, which is _suggesting_ that there might be a bug in the Fenix A320 installer. Have you installed and uninstalled any other software like that?

**Comment by RoystonS** [comment]
This is now the second broken `exe.xml` file I've seen, with the Fenix A320 in it and exactly the same problem.
See also #53

**Comment by cigayi** [comment]
First off, thank you, I haven’t coded since compsci classes in uni 20+ years ago.  As for other addons, besides fenix I have the fwb 320 and salty, both using the fwb installer. Hope this helps you with future exl file issues. 
Cigayi


Sent from Yahoo Mail for iPhone


On Sunday, October 30, 2022, 10:59, Royston Shufflebotham ***@***.***> wrote:




Hi @cigayi

Your exe.xml file is missing a close </Launch.Addon> line just before the end. Here's what you need:
<?xml version="1.0" encoding="Windows-1252"?>
<SimBase.Document Type="Launch" version="1,0">
	<Descr>Launch</Descr>
	<Filename>exe.xml</Filename>
	<Disabled>False</Disabled>
	<Launch.ManualLoad>False</Launch.ManualLoad>
	<Launch.Addon>
		<Name>FenixA320</Name>
		<Disabled>False</Disabled>
		<Path>C:\Program Files\FenixSim A320\deps\FenixBootstrapper.exe</Path>
	</Launch.Addon>
</SimBase.Document>

Out of interest, could I ask what addons you've installed and uninstalled in the past? Your exe.xml file only seems to have one thing in it, and that's broken, which is suggesting that there might be a bug in the Fenix A320 installer. Have you installed and uninstalled any other software like that?

**Comment by RoystonS** [comment]
Thanks @cigayi. If this is a standard fault of one of those installers, I'll teach BBL about it so that it can automatically fix this one.
